### ISSUE TITLE
BR: Error when trying to add integration

### ISSUE THREAD

**Issue by rasssta** [JohNan/homeassistant-wellbeing#2]
I've installed via HACS and restarted HASS.

When I try to add the Wellbeing integration I get the following error message in the Web UI:

"Config flow could not be loaded"

home-assistant.log:

`2021-05-14 20:15:34 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration wellbeing: cannot import name 'ConfigEntryAuthFailed' from 'homeassistant.exceptions' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/exceptions.py)
`

**Comment by rasssta** [comment]
manifest.json contain: 
"version": "v0.0.0"

...when version is v0.0.1

**Comment by rasssta** [comment]
Seems like the config issue was related to some missing features in 2021.4.6, it works fine in 2021.5.3 :)

**Comment by JohNan** [comment]
@rasssta so all good? Can the issue be closed?

**Comment by rasssta** [comment]
It works for me. Version is still wrong in a couple of places. 

https://github.com/JohNan/homeassistant-wellbeing/blob/1cfc48e518d5ea4446590c0fb40501c39959005a/custom_components/wellbeing/manifest.json#L11
https://github.com/JohNan/homeassistant-wellbeing/blob/32b20d598f1e80263c20fb56bf2d3fdb87932b9a/custom_components/wellbeing/const.py#L6
https://github.com/JohNan/homeassistant-wellbeing/blob/580bbd4366aea1be3beef9d7d0f5574ca23e2b01/manage/update_manifest.py#L9

And hacs.json should be updated to state HASS 2021.5.0 as minimum version I guess?

https://github.com/JohNan/homeassistant-wellbeing/blob/main/hacs.json#L6

**Comment by JohNan** [comment]
Thanks. I'll update it after the weekend!

**Comment by eulvik** [comment]
I had exactly the same problem. Disappeared after upgrading to latest Home Assistant version.

**Comment by JohNan** [comment]
Should be fixed in https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v0.0.2
